kurokobo/awx-on-k3s

README.md, base/awx.yaml, builder/README.md, containergroup/README.md, galaxy/README.md, git/README.md, runner/README.md, tips/README.md, tips/deploy-older-operator.md, tips/https-redirection.md
=> feat: bump operator version to 0.14.0

README.md
Changing 1 section of code to make it easier for users to follow. took me 15 mins to figure out i needed to run something else
=> Fixed confusing part in readme.md

README.md, acme/README.md, acme/issuer.yaml, acme/kustomization.yaml, acme/namespace.yaml
=> feat: add guide to use with public ACME CA

README.md, tips/README.md, tips/upgrade-operator.md
=> feat: enhance upgrade guide

README.md, galaxy/README.md, tips/README.md, tips/expose-hosts.md, tips/troubleshooting.md, tips/upgrade-operator.md
=> feat: add troubleshooting guide

README.md, tips/README.md, tips/external-db.md
=> feat: add guide to use external database

README.md, base/awx.yaml, base/pv.yaml
=> feat: add hardware requirements

README.md, acme/README.md, backup/ansible/README.md, base/awx.yaml, restore/README.md, tips/troubleshooting.md, tips/upgrade-operator.md
=> feat: bump operator version to 0.20.1

README.md, acme/kustomization.yaml, acme/namespace.yaml, backup/ansible/README.md, backup/kustomization.yaml, backup/namespace.yaml, base/awx.yaml, base/kustomization.yaml, base/namespace.yaml, restore/README.md, restore/kustomization.yaml, restore/namespace.yaml, tips/README.md, tips/troubleshooting.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 0.21.0

README.md, backup/ansible/README.md, base/awx.yaml, base/kustomization.yaml, tips/troubleshooting.md, tips/version-mapping.md
Hello,
I have updated the repo to the latest versions. I hope that I did not miss anything. 
Feel free to make any required changes.
Best regards
Jens
=> Update AWX to 21.2.0 and AWX Operator to 0.23.0

tips/troubleshooting.md
=> fix: fix syntax error in yaml for provisioning callback

README.md, acme/README.md, backup/ansible/README.md, base/awx.yaml, base/kustomization.yaml, base/pv.yaml, galaxy/README.md, galaxy/pulp/pv.yaml, git/deployment.yaml, restore/README.md, restore/awxrestore.yaml, restore/pv.yaml, tips/dockerhub-rate-limit.md, tips/external-db.md, tips/https-redirection.md, tips/troubleshooting.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump awx operator version to 0.26.0 and modify pv and hostpath for psql 13

README.md, backup/ansible/README.md, backup/ansible/project/backup.yml, base/awx.yaml, containergroup/README.md, galaxy/README.md, galaxy/pulp/galaxy.yaml, git/README.md, registry/README.md, restore/README.md, tips/expose-hosts.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump awx operator version to 0.28.0

README.md, backup/ansible/README.md, base/awx.yaml, base/dockerconfig.json, base/kustomization.yaml, restore/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 0.29.0

README.md, backup/ansible/README.md, base/awx.yaml, restore/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 0.30.0

README.md, acme/README.md, backup/ansible/README.md, backup/awxbackup.yaml, base/awx.yaml, builder/README.md, builder/requirements.txt, builder/requirements.yml, restore/awxrestore.yaml, runner/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.0.0

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, base/awx.yaml, git/README.md, registry/README.md, restore/README.md, tips/https-redirection.md, tips/troubleshooting.md, tips/trust-custom-ca.md, tips/version-mapping.md
=> feat: bump operator version to 1.1.0

README.md, tips/README.md, tips/alternative-methods.md
=> feat: add new guide for helm and olm

README.md, backup/ansible/README.md, base/awx.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.1.1

galaxy/README.md, galaxy/pulp/galaxy.yaml
=> feat: bump pulp operator version to 1.0.0-alpha.4

README.md, backup/ansible/README.md, base/awx.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.1.2

README.md, backup/ansible/README.md, base/awx.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.1.3

backup/ansible/README.md
=> docs: add note for inventory in the backup guide

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, base/awx.yaml, galaxy/README.md, galaxy/all-in-one/kustomization.yaml, galaxy/pulp/galaxy.yaml, git/deployment.yaml, git/kustomization.yaml, registry/deployment.yaml, registry/kustomization.yaml, restore/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.1.4

README.md, backup/README.md, backup/ansible/README.md, base/awx.yaml, restore/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.2.0

README.md, backup/ansible/README.md, base/awx.yaml, builder/README.md, restore/README.md, runner/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.3.0

tips/troubleshooting.md, tips/trust-custom-ca.md, tips/use-kerberos.md
=> docs: improve tips

README.md, backup/ansible/README.md, base/awx.yaml, git/README.md, git/kustomization.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 1.4.0

README.md, backup/ansible/README.md, base/awx.yaml, restore/README.md, tips/troubleshooting.md, tips/trust-custom-ca.md, tips/version-mapping.md
=> feat: bump operator version to 2.0.0

README.md, acme/README.md, backup/ansible/README.md, base/awx.yaml, tips/troubleshooting.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.0.1

README.md, acme/README.md, backup/ansible/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.1.0

galaxy/README.md, galaxy/pulp/galaxy.yaml
=> feat: bump pulp operator version to 1.0.0-alpha.6

README.md, backup/ansible/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.2.0

README.md, backup/ansible/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.2.1

galaxy/README.md, galaxy/pulp/galaxy.yaml
=> feat: bump galaxy ng version to 4.7.0

README.md, acme/README.md, backup/ansible/README.md, base/awx.yaml, galaxy/README.md, galaxy/pulp/galaxy.yaml, runner/README.md, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.3.0, pulp operator version to 1.0.0-alpha.8

tips/trust-custom-ca.md
=> docs: add guide to trust custom ca for jobs

README.md, operator/kustomization.yaml, tips/upgrade-operator.md
=> feat: use kustomize to deploy operator instead of make

README.md, acme/README.md, backup/ansible/README.md, git/kustomization.yaml, operator/kustomization.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.5.0

README.md, rulebooks/README.md, rulebooks/controller/eda.yaml, rulebooks/controller/kustomization.yaml, rulebooks/controller/pv.yaml, rulebooks/demo_mqtt.yaml, rulebooks/demo_webhook.yaml, rulebooks/mqtt/broker/deployment.yaml, rulebooks/mqtt/broker/kustomization.yaml, rulebooks/mqtt/broker/namespace.yaml, rulebooks/mqtt/broker/service.yaml, rulebooks/mqtt/de/Dockerfile, rulebooks/operator/kustomization.yaml, rulebooks/webhook/ingress.yaml
=> feat: add guides for eda controller

README.md, backup/ansible/README.md, operator/kustomization.yaml, tips/troubleshooting.md, tips/version-mapping.md
=> feat: bump operator version to 2.5.1

README.md, backup/ansible/README.md, galaxy/README.md, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, runner/README.md, tips/troubleshooting.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.5.2

restore/README.md, tips/https-redirection.md
Add documentation pointing out restoring after using https redirection or similar manual additions
=> manual additions restore documentation

README.md, acme/README.md, backup/ansible/README.md, galaxy/README.md, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, tips/https-redirection.md, tips/troubleshooting.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.5.3

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, backup/awxbackup.yaml, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.6.0

README.md, backup/ansible/README.md, galaxy/README.md, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, restore/README.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.7.1

README.md, acme/README.md, backup/ansible/README.md, operator/kustomization.yaml, restore/README.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.7.2

README.md
=> fix: downgrade k3s version to avoid any issues

README.md, backup/README.md, backup/ansible/README.md, git/kustomization.yaml, operator/kustomization.yaml, restore/README.md, restore/awxrestore.yaml, tips/alternative-methods.md, tips/enable-hsts.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.8.0

README.md, acme/README.md, backup/ansible/README.md, galaxy/README.md, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, restore/README.md, rulebooks/operator/kustomization.yaml, rulebooks/server/eda.yaml, tips/version-mapping.md
=> feat: bump operator version to 2.9.0

README.md, acme/README.md, backup/ansible/README.md, base/awx.yaml, galaxy/README.md, galaxy/pulp/galaxy.yaml, operator/kustomization.yaml, restore/README.md, rulebooks/README.md, rulebooks/mqtt/de/Dockerfile, tips/alternative-methods.md, tips/version-mapping.md
=> feat: bump operator version to 2.11.0

README.md, acme/README.md, backup/ansible/README.md, operator/kustomization.yaml, runner/README.md, tips/alternative-methods.md, tips/uninstall.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.12.1

README.md
List x86-64-v2 cpu requirement for AWX. Would have saved me a few hours...
=> List x86-64-v2 cpu requirement

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, builder/README.md, operator/kustomization.yaml, tips/alternative-methods.md, tips/version-mapping.md
=> feat: bump operator version to 2.12.2

README.md, backup/ansible/README.md, builder/README.md
A few changes to hopefully improve readability.
=> Readme edits

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, base/kustomization.yaml, base/pv.yaml, containergroup/README.md, galaxy/README.md, operator/kustomization.yaml, restore/README.md, restore/pv.yaml, rulebooks/README.md, runner/README.md, tips/alternative-methods.md, tips/enable-hsts.md, tips/troubleshooting.md, tips/uninstall.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump operator version to 2.13.1

README.md, argocd/README.md, argocd/example/awx.yaml, argocd/example/kustomization.yaml, argocd/ingressroute.yaml, argocd/kustomization.yaml, argocd/namespace.yaml
=> feat: add guide and resources for argocd

README.md, acme/README.md, backup/README.md, backup/ansible/README.md, builder/README.md, containergroup/README.md, galaxy/README.md, git/README.md, registry/README.md, restore/README.md, rulebooks/README.md, runner/README.md, tips/expose-hosts.md, tips/uninstall.md
=> feat: bump base os version to centos stream 9

rulebooks/README.md, rulebooks/mqtt/de/Dockerfile, rulebooks/operator/kustomization.yaml, rulebooks/server/eda.yaml
=> feat: bump eda-server-operator version to 1.0.2

README.md, backup/ansible/README.md, base/awx.yaml, galaxy/README.md, galaxy/galaxy/galaxy.yaml, galaxy/operator/kustomization.yaml, operator/kustomization.yaml, restore/README.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump awx operator version to 2.15.0

README.md
related to: https://github.com/k3s-io/k3s/issues/9983
=> fix: revert k3s version

tips/expose-hosts.md
On CentOS Stream 9, the default configuration for dnsmasq is designed to listen on `lo` only.
So to make dnsmasq accessible from CoreDNS on K3s, we have to change dnsmasq to listen on internally accessible IP address.
=> docs: update guide for exposing hosts file

README.md, acme/README.md, argocd/kustomization.yaml, backup/ansible/README.md, base/awx.yaml, galaxy/README.md, galaxy/galaxy/galaxy.yaml, galaxy/operator/kustomization.yaml, operator/kustomization.yaml, tips/expose-hosts.md, tips/upgrade-operator.md, tips/version-mapping.md
=> feat: bump awx operator version to 2.16.1, galaxy operator version to 2024.4.30

galaxy/README.md, galaxy/galaxy/galaxy.yaml, galaxy/galaxy/kustomization.yaml, galaxy/galaxy/pv.yaml, galaxy/operator/kustomization.yaml
=> feat: bump galaxy operator version to 2024.5.1

README.md, argocd/README.md, argocd/kustomization.yaml, backup/ansible/README.md, base/awx.yaml, operator/kustomization.yaml, runner/README.md, tips/alternative-methods.md, tips/version-mapping.md
=> feat: bump awx operator version to 2.17.0

tips/troubleshooting.md
=> docs: correct commands to gather logs from init containers

README.md, backup/ansible/README.md, base/awx.yaml, builder/README.md, operator/kustomization.yaml, tips/version-mapping.md
=> feat: bump awx operator version to 2.19.0

README.md, acme/README.md, argocd/kustomization.yaml, backup/ansible/README.md, base/awx.yaml, operator/kustomization.yaml, restore/README.md, tips/expose-hosts.md, tips/version-mapping.md
=> feat: bump awx operator version to 2.19.1
